name: Build Binaries

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest]
        target: [x86_64-unknown-linux-gnu]

    runs-on: ${{ matrix.platform }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Rustup
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: nightly
        override: true

    - name: Install target
      run: rustup target add ${{ matrix.target }}

    - name: Build binary
      run: cargo build --release --target ${{ matrix.target }}

    - name: Upload artifact
      if: success()
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.target }}-binary
        path: target/${{ matrix.target }}/release/
